from io import BytesIO
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (SimpleDocTemplate,Paragraph,Spacer,HRFlowable)

styles = getSampleStyleSheet()

TITLE = styles["Heading1"]
TITLE.fontName = "Helvetica-Bold"
TITLE.fontSize = 28
TITLE.textColor = colors.HexColor("#0F4C81")
TITLE.spaceAfter = 25

HEADING = styles["Heading2"]
HEADING.fontName = "Helvetica-Bold"
HEADING.fontSize = 17
HEADING.textColor = colors.HexColor("#0F4C81")
HEADING.spaceBefore = 22
HEADING.spaceAfter = 10

NORMAL = styles["BodyText"]
NORMAL.fontName = "Helvetica"
NORMAL.fontSize = 11
NORMAL.leading = 20
NORMAL.spaceAfter = 8

META = styles["BodyText"]
META.fontSize = 12
META.leading = 20

def divider(story):
    story.append(
        HRFlowable(
            width="100%",
            thickness=1.2,
            color=colors.HexColor("#0F4C81"),
            spaceBefore=6,
            spaceAfter=12,
    )
)

def add_cover_page(
    story,
    report,
):
    title = report.title
    industry = report.industry
    audience = report.target_audience

    story.append(
        Paragraph("StartupForgeAI",TITLE,))

    story.append(
        Paragraph("AI Startup Business Report",HEADING))

    story.append(Spacer(1, 0.4 * inch))

    divider(story)

    story.append(
        Paragraph(f"<b>Startup</b><br/>{title}",META))

    story.append(
        Paragraph(f"<b>Industry</b><br/>{industry}",META))

    story.append(
        Paragraph(f"<b>Target Audience</b><br/>{audience}",META))

    story.append(
        Paragraph("<b>Generated On</b><br/>"+ datetime.now().strftime("%d %B %Y"),META))

    story.append(Spacer(1, 0.4 * inch))

    divider(story)    

def add_heading(story, title: str):

    story.append(Spacer(1, 0.25 * inch))

    story.append(
        Paragraph(title.upper(),HEADING))

    divider(story)

def add_paragraph(
    story,
    text: str,
):
    if not text:
        return

    story.append(
        Paragraph(str(text),NORMAL))        

def add_bullet_list(
    story,
    items,
):

    if not items:
        return

    for item in items:
        story.append(
            Paragraph(f"• {item}",NORMAL))

def add_key_value(
    story,
    key,
    value,
):

    story.append(
        Paragraph(f"<b>{key}</b>",NORMAL))

    story.append(
        Paragraph(str(value),NORMAL))

    story.append(Spacer(1, 0.1 * inch))

def add_competitors(
    story,
    competitors,
):

    if not competitors:
        return

    for competitor in competitors:

        story.append(
            Paragraph(f"<b>{competitor['name']}</b>",NORMAL))

        story.append(
            Paragraph(competitor["description"],NORMAL))

        story.append(
            Spacer(1,0.12 * inch))

def add_page_number(canvas, doc):

    canvas.saveState()
    canvas.setFont("Helvetica",9)
    canvas.setFillColor(colors.grey)
    canvas.drawRightString(560,20,f"Page {doc.page}")
    canvas.restoreState()

def add_footer(canvas, doc):

    canvas.saveState()
    canvas.setFont("Helvetica",9)
    canvas.setFillColor(colors.grey)
    canvas.drawString(40,20,"Generated by StartupForgeAI")
    canvas.restoreState()

def decorate_page(canvas, doc):

    add_footer(canvas,doc)
    add_page_number(canvas,doc)



def generate_pdf(report):

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    story = []

    add_cover_page(story,report)

    ai_report = report.report
    market = ai_report.get("market", {})

    add_heading(story,"Market Analysis")
    add_key_value(story,"Market Size",market.get("market_size", "-"))
    add_heading(story,"Market Trends")
    add_bullet_list(story,market.get("market_trends", []))
    add_heading(story,"Target Customers")
    add_bullet_list(story,market.get("target_customers", []))
    add_heading(story,"Customer Pain Points")
    add_bullet_list(story,market.get("customer_pain_points", []))


    competitors = ai_report.get("competitors", {})

    add_heading(story,"Competitor Analysis")
    add_key_value(story,"Market Gap",competitors.get("market_gap", "-"))
    add_heading(story,"Advantages")
    add_bullet_list(story,competitors.get("advantages", []))
    add_heading(story,"Disadvantages")
    add_bullet_list(story,competitors.get("disadvantages", []))
    add_heading(story,"Top Competitors")
    add_competitors(story,competitors.get("top_competitors", []))

    swot = ai_report.get("swot", {})

    add_heading(story, "SWOT Analysis")
    add_key_value(story, "Strengths", "")
    add_bullet_list(story, swot.get("strengths", []))
    add_key_value(story, "Weaknesses", "")
    add_bullet_list(story, swot.get("weaknesses", []))
    add_key_value(story, "Opportunities", "")
    add_bullet_list(story, swot.get("opportunities", []))
    add_key_value(story, "Threats", "")
    add_bullet_list(story, swot.get("threats", []))

    business = ai_report.get("business", {})

    add_heading(story, "Business Model")
    add_key_value(story,"Business Model",business.get("business_model", "-"))
    add_key_value(story,"Value Proposition",business.get("value_proposition", "-"))
    add_key_value(story,"Pricing Strategy",business.get("pricing_strategy", "-"))
    add_heading(story,"Customer Segments")
    add_bullet_list(story,business.get("customer_segments", []))
    add_heading(story,"Revenue Streams")
    add_bullet_list(story,business.get("revenue_streams", []))
    
    technology = ai_report.get("technology", {})

    add_heading(story, "Technical Architecture")
    add_key_value(story,"Frontend",technology.get("frontend", "-"))
    add_key_value(story,"Backend",technology.get("backend", "-"))
    add_key_value(story,"Database",technology.get("database", "-"))
    add_key_value(story,"Cloud",technology.get("cloud", "-"))
    add_key_value(story,"DevOps",technology.get("devops", "-"))
    add_key_value(story,"AI Stack",technology.get("ai_stack", "-"))
    add_key_value(story,"Authentication",technology.get("authentication", "-"))
    add_heading(story,"Integrations")
    add_bullet_list(story,technology.get("integrations", []))

    roadmap = ai_report.get("roadmap", {})

    add_heading(story, "Project Roadmap")

    for phase in [
        "planning",
        "mvp",
        "beta",
        "launch",
        "scaling",
    ]:

        add_key_value(story,phase.upper(),"")

    add_bullet_list(story,roadmap.get(phase, []))


    doc.build(
        story,
        onFirstPage=decorate_page,
        onLaterPages=decorate_page,
    )

    buffer.seek(0)

    return buffer